### ISSUE TITLE
Inquiry Regarding Nginx Derivative – Thanks and Next Steps

### ISSUE THREAD

**Issue by Sokrates1989** [iiriix/docker-swarm-wordpress#2]
Hi Iiriix,

I hope this message finds you well. My name is Patrick (https://github.com/Sokrates1989), and although we haven’t had the chance to meet yet, I’ve been working with the Nginx derivative you created to place it between Traefik and WordPress.

First off, I want to sincerely thank you for the fantastic work you’ve done on this project. It’s been incredibly helpful, and I’ve recently made some updates and improvements, which you can check out here: https://github.com/Sokrates1989/swarm-wordpress-nginx. Of course, I’ve adhered to the license agreement, linked to your account, and made it public. If I’ve overlooked anything or if you have any preferences for changes, please feel free to let me know.

As part of my updates, I wanted to ask if you might consider releasing a new version of the docker image "iiriix/nginx-wp:latest" with the most up-to-date Nginx version. Alternatively, if you could share how you originally built the image, I’d be happy to take on the task of creating and maintaining it myself.

Looking forward to hearing from you, and thanks again for your contributions to this project!

Best regards,
Patrick ([Sokrates1989](https://github.com/Sokrates1989))

**Comment by Sokrates1989** [comment]
Hi Iiriix,

I hope you're doing well! I just wanted to follow up on my previous message from September 7th. I completely understand if you're busy, but I wanted to kindly check if you had a chance to consider my request regarding releasing an updated version of the Nginx derivative, or alternatively, sharing how you originally built the image. I'd still be happy to take over the task if that works better for you.

Looking forward to hearing from you when you have the time. Thanks again for all your contributions to the project!

Best regards,
Patrick

**Comment by Kahtnipp** [comment]
Hey Patrick, (@Sokrates1989 )
I'm not associated with this project but I'm just now seeing your messages and updates to the project. Great work! 
I'm about to pull your images and give it a test run.

I'm pretty new to docker and kubernetes so I've been able to learn a lot from this project, but I can also recognize that I have a long way to go, so if I happen to give any incorrect information, know that it's simply due to my ignorance on the subjects. 

I was also super curious how he was able to add the nginx image yet it doesn't show up in his repositories list. 

If you look in the docker_wordpress_swarm apps  / nginx folder, you'll discover a [Dockerfile ](https://github.com/iiriix/docker-swarm-wordpress/blob/master/apps/nginx/Dockerfile) that you can use to build and push your own, updated version of the image. 

You can run a docker build command on the Dockerfile and that will push it to the main Docker Hub.

I built my first image just a few days ago for a lean version of fmp-php...( [leanphp](https://medium.com/@emmanuelmerali/a-lean-base-docker-image-for-php-63ded6c13733) ) I've been working to get these two projects jiving together. The updates you've made to this project are impressive! Thank you for all of your time and work that you've put into it!

docker pull kahtnipp/kahtnipp_dot_art:lean-php-base

That image is pretty much a direct copy pasta from this article by Emmanuel Merali


Good luck with the nginx Dockerfile 

Be sure to check out [Mark Hilton's](https://github.com/markhilton?tab=repositories) repo for some other goodies.

**Comment by Sokrates1989** [comment]
Hi @Kahtnipp,

Thank you so much for your kind and helpful message! I’m glad to hear my updates have been useful for your setup. I appreciate pointing out the location of the Dockerfile so much—that will definitely help me re-create the image with the latest versions. I'll be sure to post an update once I find the time to implement it.

Good luck with your project, and please feel free to reach out if you have any questions about my setup or implementation. Maybe by answering your questions, we can both learn and improve our projects together.

Thanks again for your support and insights!

Best regards,
Patrick

**Comment by Sokrates1989** [comment]
I've created a newer version of the Alpine NGINX image using this [Dockerfile](https://github.com/Sokrates1989/swarm-wordpress-nginx/blob/main/apps/nginx/Dockerfile), available under [sokrates1989/alpine-nginx-wp:latest](https://hub.docker.com/r/sokrates1989/alpine-nginx-wp) and [sokrates1989/alpine-nginx-wp:1.26.2](https://hub.docker.com/r/sokrates1989/alpine-nginx-wp). This image is based on Alpine 3.20.3 and uses NGINX 1.26.2, aligning the tag with the NGINX version for easier tracking.

For further details on the publish and build process, I've added a section to the [README](https://github.com/Sokrates1989/swarm-wordpress-nginx#developermaintainer-information), specifically for developers looking to publish newer images.
